# Generated by Django 5.1.4 on 2024-12-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_background_picture_customuser_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
