# Generated by Django 5.1.4 on 2025-01-21 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_likes_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reports',
            field=models.ManyToManyField(related_name='reported_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
