# Generated by Django 5.1.4 on 2025-02-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(default='100', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
