# Generated by Django 5.1.4 on 2025-02-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_subscriptionplan_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.IntegerField(default=100, help_text='In cents'),
        ),
    ]
